name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches_ignore: []

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup conda environment
      run: conda create --quiet --name map pytest

    - name: Run tests
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate map
        pip install -r scripts/requirements.txt
        pytest -v -x tests/test_*.py
